name: Release
on:
  workflow_call:
    inputs:
      mc_version:
        description: "Minecraft version"
        required: true
        type: string
      build:
        description: "Paper build number"
        required: true
        type: number
      current_build:
        description: "Current Paper build number"
        required: true
        type: number
      commit:
        description: "Commit hash of the build"
        required: true
        type: string
      prerelease:
        description: "Whether the release is a pre-release"
        default: false
        required: true
        type: boolean
      version_check:
        description: "Whether the new version is newer or equal to the current version"
        default: false
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      mc_version:
        description: "Minecraft version"
        required: true
        type: string
      build:
        description: "Paper build number"
        required: true
        type: number
      current_build:
        description: "Current Paper build number"
        required: true
        type: number
      commit:
        description: "Commit hash of the build"
        required: true
        type: string
      prerelease:
        description: "Whether the release is a pre-release"
        default: false
        required: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: fish {0}
    if: >-
      inputs.commit != 'null'
      && (inputs.version_check || github.event_name == 'workflow_dispatch')
      && inputs.build > inputs.current_build
    steps:
      - name: Install fish Shell
        uses: fish-actions/install-fish@v1.1.0
      - name: Checkout PaperMC/Paper
        uses: actions/checkout@v3
        with:
          repository: PaperMC/Paper
          ref: ${{ inputs.commit }}
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace
      - name: Drop Bad Patches
        env:
          BAD_PATCHES: |-
            Fix sand duping
            Fix dangerous end portal logic
        working-directory: Paper-Server
        run: |
          for msg in (string split \n $BAD_PATCHES)
              if set -l hash (git rev-parse ":/^$msg" 2>/dev/null)
                  echo "Dropping commit: "(git log --oneline -1 $hash)
                  git rebase --onto $hash^ $hash -q && echo Success || echo Fail
              else
                  echo "::warning::Commit not found: $msg"
              end
          end
      - name: Build Paperclip jar
        env:
          BUILD_NUMBER: ${{ inputs.build }}
        run: |
          ./gradlew createReobfPaperclipJar --stacktrace
      - name: Prepare Release
        env:
          fish_trace: 1
        run: |
          sudo wget -nv --show-progress --progress=bar:force:noscroll https://github.com/BLAKE3-team/BLAKE3/releases/latest/download/b3sum_linux_x64_bin -O /usr/bin/b3sum || exit 1
          sudo chmod +x /usr/bin/b3sum
          mv build/libs/paper-paperclip-(grep -Po '^version=\K.+$' gradle.properties)-reobf.jar paper.jar
          b3sum paper.jar > paper.b3sum
          echo "[![${{ github.workflow }}](https://flat.badgen.net/badge/${{ github.workflow }}/%23${{ github.run_number }}/green?icon=github)](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          ## Changelog
          " > release_note.md
          if test (math ${{ inputs.build }} - ${{ inputs.current_build }}) -gt 1
              curl -sLf https://api.papermc.io/v2/projects/paper/version_group/(string match -r '\d+\.\d+' ${{ inputs.mc_version }})/builds\
              | jq -r '.builds[] | select(.build > ${{ inputs.current_build }} and .build <= ${{ inputs.build }})
                  | "- **\(.build)**", "  - \((.changes[] | "[PaperMC/Paper@\(.commit[:7])] \(.summary)") // "No changes")"'
          else
              curl -sLf https://api.papermc.io/v2/projects/paper/versions/${{ inputs.mc_version }}/builds/${{ inputs.build }}\
              | jq -r '"- \((.changes[] | "[PaperMC/Paper@\(.commit[:7])] \(.summary)") // "No changes")"'
          end | string replace -ra '#\d+' 'PaperMC/Paper$0' | string replace -ra ' (@\S+)' ' `$1`' >> release_note.md
          echo "
          ## BLAKE3 checksum
          
          ```
          $(cat paper.b3sum)
          ```" >> release_note.md
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: ${{ inputs.mc_version }}-${{ inputs.build }}
          tag_name: ${{ inputs.mc_version }}-${{ inputs.build }}
          prerelease: ${{ inputs.prerelease }}
          body_path: release_note.md
          files: |
            paper.jar
            paper.b3sum
