name: Release
on:
  workflow_call:
    inputs:
      mc_version:
        description: "Minecraft version"
        required: true
        type: string
      build:
        description: "Paper build number"
        required: true
        type: string
      current_build:
        description: "Current Paper build number"
        required: false
        type: string
      commit:
        description: "Commit hash of the build"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      mc_version:
        description: "Minecraft version"
        required: true
        type: string
      build:
        description: "Paper build number"
        required: true
        type: string
      current_build:
        description: "Current Paper build number"
        required: false
        type: string
      commit:
        description: "Commit hash of the build"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: fish {0}
    strategy:
      matrix:
        java: [17]
      fail-fast: true
    env:
      mc_version: ${{ inputs.mc_version || github.event.inputs.mc_version }}
      build: ${{ inputs.build || github.event.inputs.build }}
      current_build: ${{ inputs.current_build || github.event.inputs.current_build }}
      commit: ${{ inputs.commit || github.event.inputs.commit }}
    steps:
      - name: Install fish Shell
        uses: fish-actions/install-fish@v1.1.0
      - name: Checkout PaperMC/Paper
        uses: actions/checkout@v3.0.2
        with:
          repository: PaperMC/Paper
          ref: ${{ env.commit }}
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.3.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace
      - name: Drop Bad Patches
        env:
          BAD_PATCHES: |-
            Fix sand duping
            Fix dangerous end portal logic
            Fix nothing mlg
        working-directory: Paper-Server
        run: |
          for msg in (string split \n $BAD_PATCHES)
              if set -l hash (git rev-parse ":/^$msg" 2>/dev/null)
                  echo "Dropping commit: "(git log --oneline -1 $hash)
                  git rebase --onto $hash^ $hash -q && echo Success || echo Fail
              else
                  echo "::warning::Commit not found: $msg"
              end
          end
      - name: Build Paperclip jar
        env:
          BUILD_NUMBER: ${{ env.build }}
        run: |
          ./gradlew createReobfPaperclipJar --stacktrace
      - name: Prepare Release
        run: |
          sudo wget -nv --show-progress --progress=bar:force:noscroll https://github.com/BLAKE3-team/BLAKE3/releases/latest/download/b3sum_linux_x64_bin -O /usr/bin/b3sum
          sudo chmod +x /usr/bin/b3sum
          mv build/libs/paper-paperclip-(grep -Po '^version=\K.+$' gradle.properties)-reobf.jar paper.jar
          b3sum paper.jar > paper.b3sum
          echo -e "## Changelog\n" > release_note.md
          if test (math $build - $current_build) -gt 1
              curl -sLf https://api.papermc.io/v2/projects/paper/version_group/(string match -r '\d+\.\d+' ${{ env.mc_version }})/builds\
              | jq -r '.builds[] | select(.build > '$current_build' and .build <= '$build')
                  | "- **\(.build)**", "  - \((.changes[] | "[PaperMC/Paper@\(.commit[:7])] \(.summary)") // "No changes")"'
          else
              curl -sLf https://api.papermc.io/v2/projects/paper/versions/${{ env.mc_version }}/builds/$build\
              | jq -r '"- \((.changes[] | "[PaperMC/Paper@\(.commit[:7])] \(.summary)") // "No changes")"'
          end | string replace -ra '#\d+' 'PaperMC/Paper$0' >> release_note.md
          echo -e "\n## BLAKE3 checksum\n\n```\n$(cat paper.b3sum)\n```" >> release_note.md
      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: ${{ env.mc_version }}-${{ env.build }}
          tag_name: ${{ env.mc_version }}-${{ env.build }}
          body_path: release_note.md
          files: |
            paper.jar
            paper.b3sum
